import type { MaterialProduct } from '@/types/material';

const img = (file: string) => `/products/materials/${file}`;

export const MATERIAL_CATEGORIES = [
  'ทั้งหมด',
  'ปูนและคอนกรีต',
  'เหล็กโครงสร้าง',
  'ไม้แบบและไม้แปรรูป',
  'หลังคาและผนัง',
  'สีและเคมีภัณฑ์',
  'ระบบประปา',
  'ระบบไฟฟ้า',
  'เครื่องมือช่าง',
] as const;

export const DEMO_MATERIALS: MaterialProduct[] = [
  {
    id: 'cement-tiger',
    name: 'ปูนซีเมนต์ ตราลูกโลก',
    category: 'ปูนและคอนกรีต',
    spec: '50 กก. | มอก. 15',
    description:
      'ปูนซีเมนต์ปอร์ตแลนด์ตราลูกโลก คุณภาพมาตรฐาน มอก. เหมาะงานเทคอนกรีต ฐานราก และโครงสร้างทั่วไป',
    price: 178,
    unit: 'ถุง',
    stock: 1250,
    stock_status: 'พร้อมส่ง',
    image_url: img('cement-tiger.png'),
    is_active: true,
  },
  {
    id: 'steel-db16',
    name: 'เหล็กเส้นกลม DB16',
    category: 'เหล็กโครงสร้าง',
    spec: 'ยาว 12 ม. | มอก.',
    description: 'เหล็กเส้นกลม SD40 สำหรับงานโครงสร้างคอนกรีตเสริมเหล็ก มาตรฐานมอก.',
    price: 285,
    unit: 'เส้น',
    stock: 480,
    stock_status: 'พร้อมส่ง',
    image_url: img('steel-db16.png'),
    is_active: true,
  },
  {
    id: 'wood-formwork',
    name: 'ไม้แบบสน 2"x4"x4ม.',
    category: 'ไม้แบบและไม้แปรรูป',
    spec: 'เกรด A',
    description: 'ไม้สนแปรรูปสำหรับงานแบบหล่อคอนกรีต ผิวเรียบ แข็งแรง ใช้งานซ้ำได้',
    price: 145,
    unit: 'ท่อน',
    stock: 320,
    stock_status: 'พร้อมส่ง',
    image_url: img('wood-formwork.png'),
    is_active: true,
  },
  {
    id: 'metal-roof-sheet',
    name: 'เมทัลชีท หลังคา สีน้ำเงิน',
    category: 'หลังคาและผนัง',
    spec: 'หนา 0.35 มม. | ยาว 4 ม.',
    description: 'แผ่นเมทัลชีทเคลือบสีกันสนิม ทนฝนและแดด เหมาะงานหลังคาและผนังอาคาร',
    price: 185,
    unit: 'แผ่น',
    stock: 210,
    stock_status: 'พร้อมส่ง',
    image_url: img('metal-roof-sheet.png'),
    is_active: true,
  },
  {
    id: 'primer-paint',
    name: 'สีรองพื้นปูน TOA',
    category: 'สีและเคมีภัณฑ์',
    spec: 'ถัง 5 แกลลอน',
    description: 'สีรองพื้นปูนคุณภาพสูง ยึดเกาะดี ป้องกันความชื้นก่อนทาสีจบ',
    price: 1250,
    unit: 'ถัง',
    stock: 45,
    stock_status: 'เหลือน้อย',
    image_url: img('primer-paint.png'),
    is_active: true,
  },
  {
    id: 'pvc-pipe',
    name: 'ท่อ PVC 4 นิ้ว (หนา)',
    category: 'ระบบประปา',
    spec: 'ยาว 4 ม. | มอก.',
    description: 'ท่อ PVC ชั้น 8.5 ทนความดัน ใช้งานระบบน้ำดี น้ำทิ้ง และระบบชลประทาน',
    price: 168,
    unit: 'ท่อน',
    stock: 380,
    stock_status: 'พร้อมส่ง',
    image_url: img('pvc-pipe.png'),
    is_active: true,
  },
  {
    id: 'electric-wire',
    name: 'สายไฟ VVF 2x2.5',
    category: 'ระบบไฟฟ้า',
    spec: 'ม้วน 100 ม. | มอก.',
    description: 'สายไฟทองแดงหุ้มฉนวน VVF 2x2.5 มม² สำหรับงานไฟฟ้าภายในอาคาร',
    price: 1250,
    unit: 'ม้วน',
    stock: 28,
    stock_status: 'เหลือน้อย',
    image_url: img('electric-wire.png'),
    is_active: true,
  },
  {
    id: 'tile-adhesive',
    name: 'ปูนกาว C2TE สำหรับกระเบื้อง',
    category: 'สีและเคมีภัณฑ์',
    spec: 'ถุง 20 กก.',
    description: 'ปูนกาวยืดหยุ่นสูง สำหรับปูกระเบื้องพื้นและผนัง ยึดเกาะแน่น กันน้ำซึม',
    price: 245,
    unit: 'ถุง',
    stock: 156,
    stock_status: 'พร้อมส่ง',
    image_url: img('tile-adhesive.png'),
    is_active: true,
  },
  {
    id: 'construction-sand',
    name: 'ทรายหยาบสำหรับงานก่อสร้าง',
    category: 'ปูนและคอนกรีต',
    spec: 'ถุง 50 กก.',
    description: 'ทรายหยาบคัดเกรด สำหรับผสมคอนกรีต เทปูน และงานฐานราก',
    price: 65,
    unit: 'ถุง',
    stock: 800,
    stock_status: 'พร้อมส่ง',
    image_url: img('construction-sand.png'),
    is_active: true,
  },
  {
    id: 'hand-tools',
    name: 'ชุดเครื่องมือช่างมือ',
    category: 'เครื่องมือช่าง',
    spec: 'เกรียง + ค้อน',
    description: 'ชุดเครื่องมือช่างพื้นฐานสำหรับงานก่อสร้างและงานฉาบปูน',
    price: 320,
    unit: 'ชุด',
    stock: 95,
    stock_status: 'พร้อมส่ง',
    image_url: img('hand-tools.png'),
    is_active: true,
  },
];
