/**
 * AUTO-GENERATED by scripts/inject-supabase-env.mjs — อย่าแก้มือ
 * Source: VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY at build time
 */
window.__RACHAWEI_SUPABASE__ = {
  url: "",
  anonKey: "",
  configured: false
};
