/**
 * AUTO-GENERATED by scripts/inject-supabase-env.mjs — อย่าแก้มือ
 * Source: public_fallback (VITE_SUPABASE_* or public fallback)
 */
window.__RACHAWEI_SUPABASE__ = {
  url: "https://jvgfudxdwdwfumdznymu.supabase.co",
  anonKey: "sb_publishable_oG6s4HUGebJ-XRyqU5gjeg_kfKqhYnY",
  configured: true
};
