import type { DeliveryZone } from '@/types/checkout';
import type { Product } from '@/types/product';

const now = '2026-07-12T00:00:00.000Z';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-01',
    name: 'ตะกร้าหวายสี่เหลี่ยมจัตุรัส 2 ชั้น',
    description: 'ตะกร้าหวายทรงสี่เหลี่ยมจัตุรัส 2 ชั้น หูจับสูง ลายสานโปร่ง งานพิเศษสานมือ',
    category: 'พิเศษ',
    price: 890,
    unit: 'ชิ้น',
    stock: 12,
    image_url: null,
    is_active: true,
    created_at: now,
  },
  {
    id: 'demo-02',
    name: 'เก้าอี้หวาย ทรงกลม',
    description: 'เก้าอี้หวายทรงกลมสานมือ ชุดคู่พร้อมโต๊ะหวาย ดีไซน์หลังมน นั่งสบาย',
    category: 'เก้าอี้',
    price: 4500,
    unit: 'ชุด',
    stock: 4,
    image_url: null,
    is_active: true,
    created_at: now,
  },
  {
    id: 'demo-03',
    name: 'ตะกร้ากลม 2 ชั้น ถักปาก',
    description: 'ตะกร้าหวายทรงกลม 2 ชั้น ปากถักตกแต่ง หูจับสูง งานสานมือจากช่างฝีมือบ้านบุทม',
    category: 'ทรงกลม',
    price: 420,
    unit: 'ชิ้น',
    stock: 20,
    image_url: null,
    is_active: true,
    created_at: now,
  },
  {
    id: 'demo-04',
    name: 'ตะกร้าหวายทรงกลมปากหยัก',
    description: 'ตะกร้าหวายทรงกลมปากหยัก หูจับสูง ลายสานถี่ งานประณีตจากช่างบ้านบุทม',
    category: 'หูจับสูง',
    price: 350,
    unit: 'ชิ้น',
    stock: 15,
    image_url: null,
    is_active: true,
    created_at: now,
  },
  {
    id: 'demo-05',
    name: 'ตะกร้าหวายมีฝา ชุดคู่',
    description: 'ตะกร้าหวายมีฝาปิด ชุดคู่ ลายสานละเอียด เหมาะเป็นของฝาก',
    category: 'มีฝา',
    price: 520,
    unit: 'ชุด',
    stock: 10,
    image_url: null,
    is_active: true,
    created_at: now,
  },
  {
    id: 'demo-06',
    name: 'ตะกร้าหวายทรงเหลี่ยมมีฝา',
    description: 'ตะกร้าหวายทรงเหลี่ยมมีฝา หูจับมั่นคง ลายสานโปร่งตรงกลาง วางซ้อนได้สะดวก',
    category: 'ทรงเหลี่ยม',
    price: 480,
    unit: 'ชิ้น',
    stock: 3,
    image_url: null,
    is_active: true,
    created_at: now,
  },
];

export const DEMO_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 'demo-zone-01',
    name: 'สุรินทร์ — ในเมือง',
    description: 'อำเภอเมืองและพื้นที่ใกล้เคียง',
    fee: 50,
    is_active: true,
    sort_order: 1,
    created_at: now,
  },
  {
    id: 'demo-zone-02',
    name: 'สุรินทร์ — ชานเมือง',
    description: 'อำเภออื่นในจังหวัดสุรินทร์',
    fee: 80,
    is_active: true,
    sort_order: 2,
    created_at: now,
  },
  {
    id: 'demo-zone-03',
    name: 'อีสานใกล้เคียง',
    description: 'จังหวัดใกล้เคียง เช่น บุรีรัมย์ ศรีสะเกษ',
    fee: 120,
    is_active: true,
    sort_order: 3,
    created_at: now,
  },
  {
    id: 'demo-zone-04',
    name: 'กรุงเทพและปริมณฑล',
    description: 'กรุงเทพ นนทบุรี ปทุมธานี สมุทรปราการ',
    fee: 150,
    is_active: true,
    sort_order: 4,
    created_at: now,
  },
  {
    id: 'demo-zone-05',
    name: 'ทั่วประเทศ',
    description: 'จังหวัดอื่น ๆ ทั่วไทย',
    fee: 200,
    is_active: true,
    sort_order: 5,
    created_at: now,
  },
];
